name: Publish on PyPI 

on:
  release:
    types:
      - published
      
jobs:
   pypi-publish:
     name: Publish to PyPI
     runs-on: ubuntu-latest
     permissions:
       id-token: write
     steps:
       - name: Publish package distributions to PyPI
         uses: pypa/gh-action-pypi-publish@release/v1