name: Publish on PyPI 

on:
  release:
    types:
      - published
      
jobs:
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
   permissions:
      id-token: write
   steps:
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1